# syntax=docker/dockerfile:1
FROM python:3.10-slim-buster
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
CMD [ "python3", "-m", "flask", "run", "--host=0.0.0.0"]
RUN pip3 install gunicorn
COPY ./app /app
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
